### ISSUE TITLE
asyncsafe does not work on Ubuntu 14.04 x86_64

### ISSUE THREAD

**Issue by briskycat** [dwks/asyncsafe#2]
$ uname -a
Linux Ubuntu-External3 3.13.0-95-generic #142-Ubuntu SMP Fri Aug 12 17:00:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ LD_PRELOAD=./libasyncsafe.so ./test
This handler is fine
This handler is bad :(

**Comment by dwks** [comment]
This is a bug when compiled with the wrong GCC options. With -std=c99, the constructor function never gets registered because `__attribute__ (( __constructor__ ))` is a GCC extension. Use -std=gnu99 instead. Reproduced on Ubuntu 16.04 with GCC 4.8, confirmed that -std=gnu99 fixes this.

**Comment by dwks** [comment]
Fixed in 7aed2c16f297c3d753910ce57d10f2f238e70c1f -- thanks for the report!
